### ISSUE TITLE
npm run electron not working on ubuntu 16.04

### ISSUE THREAD

**Issue by Nk095291** [meghansh36/Binder#2]
after running "npm run electron" on ubuntu os it's showing the following errors.I tried removing and re-installing electron but that didn't fix the error.

![Screenshot from 2019-10-01 02-33-38](https://user-images.githubusercontent.com/37153117/65918805-301b4980-e3f8-11e9-9674-03c9f4dd2e1d.png)

**Comment by meghansh36** [comment]
Try these 2 things:
1. Run npm remove electron and then npm install --save-dev electron

2. Create a separate app by following the example from here https://electronjs.org/docs/tutorial/first-app and see if that runs.

**Comment by meghansh36** [comment]
Hi,
I have fixed the error and tested it on my linux machine. Hopefully, this will fix the issue.
