### ISSUE TITLE
No files found on system error

### ISSUE THREAD

**Issue by meghansh36** [meghansh36/Binder#4]
Incase of no files found on system, a message should be displayed instead of continous spinners.

**Comment by Nk095291** [comment]
I would like to work on it!

**Comment by meghansh36** [comment]
Okay, I am assigning the issue to you. Just to be clear on the bug, if no files are found in the specified path, a message should be shown in the system file space area NO FILES FOUND

**Comment by Nk095291** [comment]
#7

**Comment by Nk095291** [comment]
fixed this bug #7

**Comment by meghansh36** [comment]
Fixed in #7 . Closing Issue
