### ISSUE TITLE
Sort the system files according to last Modified Time

### ISSUE THREAD

**Issue by meghansh36** [meghansh36/Binder#8]
Currently system files are not sorted on the basis of last modified time. 

Required Functionality: 
1 . Use the sort function on arrays in javascript along with the a custom comparator function. 
2. You can also lookup on any inbuilt function that nodejs provides for fetching files in sorted order.

**The sorting must be performed on the server side only.**

**Comment by meghansh36** [comment]
@Nk095291 Hey, would you like to work on it?

**Comment by Nk095291** [comment]
@meghansh36  yeah sure!
